/*
 * Example #90
 * Basic file I/O functions.
 *
 * Copyright (c) 2014  Pavel Tisnovsky, Red Hat
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Red Hat nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL Pavel Tisnovsky BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include <stdio.h>
#include <stdlib.h>

#define ARRAY_SIZE 10

/* this test uses the file test.bin generated by c89_file_io.c ! */
int main(void) {
    FILE *fin;
    float value;

    fin = fopen("test.bin", "rb");
    printf("current position in a file: %d\n", ftell(fin));

    /* read first 4 bytes */
    fread(&value, sizeof(float), 1, fin);
    printf("value read from input file: %f\n", value);

    /* read the next 4 bytes */
    fread(&value, sizeof(float), 1, fin);
    printf("value read from input file: %f\n", value);

    printf("current position in a file: %d\n", ftell(fin));

    fseek(fin, 0, SEEK_SET);
    printf("current position in a file: %d\n", ftell(fin));

    /* read first 4 bytes again */
    fread(&value, sizeof(float), 1, fin);
    printf("value read from input file: %f\n", value);

    fseek(fin, -4, SEEK_END);
    printf("current position in a file: %d\n", ftell(fin));

    /* read last 4 bytes */
    fread(&value, sizeof(float), 1, fin);
    printf("value read from input file: %f\n", value);

    fclose(fin);

    return 0;
}

