/*
 * Example #90
 * Basic file I/O functions.
 */
#include <stdio.h>
#include <stdlib.h>

#define ARRAY_SIZE 10

/* this test uses the file test.bin generated by c89_file_io.c ! */
int main(void) {
    FILE *fin;
    float value;

    fin = fopen("test.bin", "rb");
    printf("current position in a file: %d\n", ftell(fin));

    /* read first 4 bytes */
    fread(&value, sizeof(float), 1, fin);
    printf("value read from input file: %f\n", value);

    /* read the next 4 bytes */
    fread(&value, sizeof(float), 1, fin);
    printf("value read from input file: %f\n", value);

    printf("current position in a file: %d\n", ftell(fin));

    fseek(fin, 0, SEEK_SET);
    printf("current position in a file: %d\n", ftell(fin));

    /* read first 4 bytes again */
    fread(&value, sizeof(float), 1, fin);
    printf("value read from input file: %f\n", value);

    fseek(fin, -4, SEEK_END);
    printf("current position in a file: %d\n", ftell(fin));

    /* read last 4 bytes */
    fread(&value, sizeof(float), 1, fin);
    printf("value read from input file: %f\n", value);

    fclose(fin);

    return 0;
}

